# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Alexis Duque'
tagline:          'PhD student at the CITI Lab of INSA de Lyon, Urbanet Team. Rtone'
description:      'A student with too many interests'
url:              http://perso.citi-lab.fr/aduque
baseurl:          '/'
paginate:         5

author:
  name: 'Alexis Duque'
  email: 'alexis.duque[at]mail[dot]insa-lyon[dot]fr'
  github: alexisduque
  twitter: alexis0duque
  linkedin: alexisduque
  google_scholar: https://scholar.google.fr/citations?user=P9BIZW0AAAAJ
  email_md5: 83124b745752d1a1b0ca2eee1af0bd48
  disqus_shortname: alexisduque
  bio: PhD student at the CITI Labs / Rtone
# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/alexisduque
